package com.datvexpress.ws.versatune.enums;

public enum ScannerControl {
    ENABLED_IDLE,
    ENABLED_PENDING,
    ENABLED_ACTIVE,
    ENABLED_ACTIVE_VLC_CONNECTED,
    ENABLED_UNLOCKED,
    ENABLED_LOCKED,
    ENABLED_READ_ERROR,
    ENABLED_NODATA,
    ENABLED_SEARCH_FAILED,
    ENABLED_SLEEP_INTERRUPTED,
    DISABLED,
    EMPTY,
    SLIDESHOW_RUNNING,
    USB_RUNNING,
    RESET_IDLE,
    TUNER_RECEIVING,
    SLIDESHOW_RUNNING_WHILE_SEARCHING,
    UNDEFINED


}
